[run]
init_cmds = [
	["webpack", "--display-modules","--display-chunks","--config","admin.config.js"],
]									# Commands run in start
watch_all = true					# Watch all sub-directories
watch_dirs = [
	"$WORKDIR/admin",
	# "$WORKDIR/admin/login",
]						# Directories to watch
watch_exts = [".js",".css",".vue"]				# Extensions to watch
ignore = [".git", "node_modules"] 	# Directories to exclude from watching
ignore_files = []					# Regexps for ignoring specific notifies
build_delay = 1500					# Minimal interval to Trigger build event
interrupt_timout = 15				# Time to wait until force kill
graceful_kill = false				# Wait for exit and before directly kill
cmds = [
	["webpack", "--display-modules","--display-chunks","--config","admin.config.js"],
]									# Commands to run

[sync]
listen_addr = ":5050"
remote_addr = ":5050"
